language: node_js
node_js:
  - "7"
os:
  - linux
before_script:
  - cp configTemplate.ts config.ts
  - cp databaseTemplate.json database.json
  - cd client
  - npm install
  - cd ../
  - npm install
script:
  - cd client
  - npm run client-prod
  - cd ../
  - npm run server-prod