language: node_js
node_js:
  - "7"
os:
  - linux
before_script:
  - cp configTemplate.ts config.ts
  - cd client
  - npm install
  - cd ../
  - touch key.pem
  - touch certificate.crt
  - touch bundle.ca-bundle
  - npm install
script:
  - npm run server-client